name: rna-clique
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - tqdm
  - pandas
  - joblib>=1.3.2
  - networkx
  - matplotlib
  - seaborn
  - scikit-bio
  - pip:
      - biopython
      - dendropy
      - nice-colorsys
      - simple-blast
      # For simulator:
      - more_itertools
      - PyYAML
  # For simulator:
  - scipy
