site_name: RNA-clique user guide
repo_url: https://github.com/actapia/rna_clique
nav:
    - Home: index.md
    - Command-line usage: usage.md
    - Installation guides:
        - Ubuntu: installation_guides/ubuntu.md
        - macOS: installation_guides/macos.md
    - Tutorials:
        - tutorials/reads2tree/README.md
plugins:
  - mike:
      # These fields are all optional; the defaults are as below...
      alias_type: symlink
      redirect_template: null
      deploy_prefix: ''
      canonical_version: 'latest'
      version_selector: true
      css_dir: css
      javascript_dir: js
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
theme:
    name: material
    features:
        - content.code.copy
