site_name: RNA-clique user guide
nav:
    - Home: index.md
    - Command-line usage: usage.md
    - Installation guides:
        - Ubuntu: installation_guides/ubuntu.md
    - Tutorials:
        - tutorials/reads2tree/README.md
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
theme:
    name: material
    features:
        - content.code.copy
