name: mkdocs

on:
  push:
    branches: ["main", "mkdocs"]

jobs:
  deploy-mkdocs:
    name: Deploy mkdocs
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@1.26
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}