name: markdown-autodocs

on:
  push:
    branches: ["main", "autodocs"]

jobs:
  auto-update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Markdown autodocs
        uses: dineshsonachalam/markdown-autodocs@v1.0.7
        with:
          output_file_paths: '[./docs/tutorials/reads2tree/README.md]'
          commit_message: Update code examples in tutorials.
