name: test-install-macos

on:
  push:
    branches: ["main", "macos"]
    paths:
      - '*'
      - '!.gitignore'
      - '!workflows/**'
      - 'workflows/test-install-macaos.yml'
      - '!test_install/**'
      - 'tests/test_install/macos.sh'
      - '!parameter_testing/**'
      - '!property_testing/**'
      - '!*.md'

jobs:
  test-install-macos-latest:
    name: Test installation on macOS.
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test installation
        run: zsh tests/test_install/macos.sh "$GITHUB_REF_NAME"
      
