name: test-install-macos

on:
  push:
    branches: ["main", "macos"]
    paths:
      - '*'
      - '!.gitignore'
      - '!.github/workflows/**'
      - '.github/workflows/test-install-macos.yml'
      - '!test_install/**'
      - 'tests/test_install/macos.sh'
      - '!parameter_testing/**'
      - '!property_testing/**'
      - '!*.md'
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  test-install-macos:
    name: Test installation on macOS
    strategy:
      matrix:
        os: [macos-14, macos-13]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
      - name: Test installation
        run: PASSWORDLESS=1 zsh tests/test_install/macos.sh "$GITHUB_REF_NAME"
      
